version: '3.8'
volumes:
  mainnet-lite-volume:
services:
  mainnet-lite:
    image: opentensor/subtensor:latest
    restart: always
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    network_mode: host
    container_name: subtensor-mainnet-lite
    volumes:
      - mainnet-lite-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec.json \
          --rpc-cors all \
          --no-mdns \
          --ws-max-connections 10000 \
          --in-peers 100 --out-peers 50 \
          --no-private-ip \
          --bootnodes /dns/bootnode.finney.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --sync warp \
          --ws-external \
          --rpc-external
